language: cpp

matrix:
  include:
    os: 
      - windows
      - linux

before_script:
  - |
    ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      export CUDA_VERSION=10.1
      echo $CUDA_VERSION
    fi
script:
  - /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Auxiliary/Build/vcvars64.bat